# Generated by Django 3.1.7 on 2021-03-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210304_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
