# Generated by Django 3.1.7 on 2021-03-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210316_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('card,', 'card'), ('cash', 'cash')], default='cash', max_length=10),
        ),
    ]
